dist: trusty
sudo: false
language: cpp
compiler: gcc

os: linux

services:
  - docker

before_install:
  - docker build . -f Dockerfile.travis -t word-detective:build
  
script:
  - ci_env=$(bash <(curl -s https://codecov.io/env))
  - docker run $ci_env word-detective:build /bin/bash -c "/word-detective/lab/docker-scripts/build-install.sh && /word-detective/lab/docker-scripts/run-tests.sh" 
