FROM alpine:3.14 as build

RUN apk add --update --no-cache \
bash \
g++ \
make \
cmake

WORKDIR /word-detective-build

COPY . /word-detective-build

RUN ./lab/docker-scripts/install-deps.sh && \
./lab/docker-scripts/build-install.sh && \
./lab/docker-scripts/run-tests.sh

#-----------------------------------------#

FROM alpine:3.14

WORKDIR /word-detective

COPY --from=build /word-detective-build/install /word-detective/install/
COPY app/render-word-detective/*.sh /word-detective/install/render-word-detective/
COPY app/render-word-detective/*.py /word-detective/install/render-word-detective/
