FROM word-detective-dependencies:v0.1

COPY . /word-detective-build

RUN ./lab/docker-scripts/build-install.sh && \
./lab/docker-scripts/run-tests.sh

RUN ./lab/docker-scripts/minify-word-detective-js.sh

#-----------------------------------------#

FROM word-detective-dependencies:v0.1

WORKDIR /word-detective

COPY --from=build /word-detective-build/install /word-detective/install/
COPY app/render-word-detective/*.sh /word-detective/install/render-word-detective/
COPY app/render-word-detective/*.py /word-detective/install/render-word-detective/

COPY --from=build /word-detective-build/word-detective-js/dist/word-detective-min.js \
/word-detective/install/word-detective-js/word-detective-min.js

COPY --from=build /word-detective-build/dictionaries/it/italian_dictionary.py \
/word-detective/bin/italian_dictionary.py
