# Use gcc as base image
FROM gcc:9.4

# Update indices for apt-get and install dependencies
RUN apt-get update && \
apt-get install --fix-missing -y \
cmake \
libboost-filesystem-dev \
libboost-system-dev \
lcov curl && \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

# Set the working directory to /app
WORKDIR /word-detective

# Copy the docker-context directory content
COPY . /word-detective

RUN ./lab/docker-scripts/deps/install-icu.sh
