FROM alpine:3.14

RUN apk add --update --no-cache \
bash \
g++ \
make \
cmake \
nodejs \
npm

WORKDIR /word-detective-build
COPY ./docker/scripts/dependencies /word-detective-build/docker/scripts/dependencies

RUN ./docker/scripts/dependencies/install-boost.sh
RUN ./docker/scripts/dependencies/install-icu.sh
